version: "3.8"
services: 
  backend: 
    build: ./server
    container_name: server_c
    ports: 
      - '4000:4000'
    volumes:
      - ./server:/app
      - ./app/node_modules
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
      